<div id='cabas'>
    <div id='cabas-title'>
        <a href="index.php?accio=cart"><h2>CART</h2></a>
    </div>
    <div id='cabas-list'>
        <ul>
            <li>
                <p>Producto</p>
                <p>x2</p>
            </li>
            <li>
                <p>Producto</p>
                <p>x2</p>
            </li>
            <li>
                <p>Producto</p>
                <p>x2</p>
            </li>
            <li>
                <p>Producto</p>
                <p>x2</p>
            </li>
            <li>
                <p>Producto</p>
                <p>x2</p>
            </li>
            <li>
                <p>Producto</p>
                <p>x2</p>
            </li>
            <li>
                <p>Producto</p>
                <p>x2</p>
            </li>
            <li>
                <p>Producto</p>
                <p>x2</p>
            </li>
            <li>
                <p>Producto</p>
                <p>x2</p>
            </li>
            <li>
                <p>Producto</p>
                <p>x2</p>
            </li>
            <li>
                <p>Producto</p>
                <p>x2</p>
            </li>
            <li>
                <p>Producto</p>
                <p>x2</p>
            </li>
            <li>
                <p>Producto</p>
                <p>x2</p>
            </li>
            <li>
                <p>Producto</p>
                <p>x2</p>
            </li>
            <li>
                <p>Producto</p>
                <p>x2</p>
            </li>
            <li>
                <p>Producto</p>
                <p>x2</p>
            </li>
            <li>
                <p>Producto</p>
                <p>x2</p>
            </li>
            <li>
                <p>Producto</p>
                <p>x2</p>
            </li>
            <li>
                <p>Producto</p>
                <p>x2</p>
            </li>
        </ul>
    </div>
    <div id='cabas-price'>
        <p>$65</p>
    </div>
    <div id='cabas-purchase'>
        <a>Purchase</a>
    </div>
</div>